# config.py
import os

SECRET_KEY = os.urandom(24)
RECAPTCHA_PUBLIC_KEY = 'YOUR_RECAPTCHA_PUBLIC_KEY'
RECAPTCHA_PRIVATE_KEY = 'YOUR_RECAPTCHA_PRIVATE_KEY'
SECURITY_PASSWORD_SALT = 'YOUR_PASSWORD_SALT'
RECAPTCHA_PARAMETERS = {'hl': 'en'}
SECURITY_PASSWORD_HASH = 'bcrypt'
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True


